import type { Metadata } from 'next';
import { Itim } from 'next/font/google';
import Header from '~/components/Header/Header';
import Footer from '~/components/Footer/Footer';
import Providers from '~/app/providers';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const itim = Itim({ subsets: ['vietnamese'], weight: '400' });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: React.ReactNode;
    params: {
        locale: string;
    };
}

export default async function RootLayout({ children, params: { locale } }: Readonly<RootLayoutProps>) {
    const messages = await getMessages();
    return (
        <NextIntlClientProvider messages={messages}>
            <html lang={locale} suppressHydrationWarning>
                <link href='/favicon.ico' rel='icon' />
                <body className={itim.className}>
                    <Providers>
                        <Header />
                        <main className='mx-4 mt-[1.5rem] min-h-[100vh] max-w-[1638px] md:mx-6 2xl:mx-auto'>
                            {children}
                        </main>
                        <Footer />
                    </Providers>
                </body>
            </html>
        </NextIntlClientProvider>
    );
}
